service:
  env: production
  secret: ${UPTRACE_SECRET}

site:
  url: ${UPTRACE_SITE_URL}
  ingest_url: ${UPTRACE_INGEST_URL}

listen:
  http:
    addr: :80
  grpc:
    addr: :4317

ch_cluster:
  cluster: uptrace
  replicated: false
  distributed: false
  shards:
    - replicas:
        - addr: ${CH_ADDR}
          database: ${CH_DATABASE}
          user: ${CH_USER}
          password: ${CH_PASSWORD}
          dial_timeout: 3s
          write_timeout: 5s
          max_retries: 3
          max_execution_time: 15s

pg:
  addr: ${PG_ADDR}
  user: ${PG_USER}
  password: ${PG_PASSWORD}
  database: ${PG_DATABASE}

ch_schema:
  compression: ZSTD(1)
  spans_index: { storage_policy: default }
  spans_data: { storage_policy: default }
  span_links: { storage_policy: default }
  logs_index: { storage_policy: default }
  logs_data: { storage_policy: default }
  events_index: { storage_policy: default }
  events_data: { storage_policy: default }
  timeseries: { storage_policy: default }
  datapoints: { storage_policy: default }

seed_data:
  update: true
  delete: true
  users:
    - key: admin
      name: Admin
      email: ${ADMIN_EMAIL}
      password: ${ADMIN_PASSWORD}
      email_confirmed: true

redis_cache:
  addrs:
    1: ${REDIS_ADDR}
  password: ${REDIS_PASSWORD}
  db: 0

logging:
  level: ${UPTRACE_LOG_LEVEL}

self_monitoring:
  dsn: ${UPTRACE_DSN}
